print('ADDITION +')
print(1+2)
print(1.2+3.5)
print(True+False)
print((3+4j)+(4+5j))
print('abc'+'cde')
print([1, 2, 'A']+[12, 'B', True])
print("+ operator can't be used with None, {set}  & {di:ct}")

print('SUBTRACTION -')
print(2-1)
print(3.5-2.1)
print(False-True)
print((12+6j)-(10-3j))
print("- opeartor can't be used with None & Collection D.S. but with {set} we can use")
s1={1, 2, 'A'}
s2={10, 2, 'B'}
print(s1-s2)
print("It works same as diff()")

print('Multiplication *')
print(2*3)
print(2.3*5)
print(True*5)
print((3+4j)*(1+23j))
print('STRandINT'*False)
print([1, 2, 'Money', False, True]*3)
print((1, False, 23.5)*2)
print("With string, list and tuple we can only multiply integers")
print("None, {set}, {di:ct} can't use * operator")
print("If * is used with collection d.s. with '-ve' or 0,then it returns the default object of that d.s.")
print('abc'*0)
print([1, 2, 'ABC']*-2)
print((1,2,2)*-100)
